name: Continuous Integration - Primeira configuração

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rodando Workflow de Continuous Integration"
      - name: Checkout do repositório
        uses: actions/checkout@v4

  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}