name: DevOps - Continuous Delivery/Deploy #exemplo

on: 
  push:
    branches:
      - main

jobs: 
  continuous-delivery: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Continuous Delivery
      uses: actions/upload-artifact@v4
      with:
        name: projeto.zip
        path: |
          "./src/app.js"
          
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: continuous-delivery

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: projeto.zip
    - name: Exibe os arquivos baixados
      run: ls -R