name: DevOps - Continuous Integration

on: pull_request

jobs:
  continuous-integration-e-testes-unitarios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instalando o Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Instalação, build e testes unitários do projeto
        run: |
          npm install -g yarn
          yarn install
          npm run build
          npm run test
          npm test -- --coverage
          env:
            SKIP_PREFLIGHT_CHECK=true
            CI:true

  docker:
    runs-on: ubuntu-latest
    needs: continuous-integration-e-testes-unitarios
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3