name: DevOps - Continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instalando o Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'
      - name: Instalação, build e testes do projeto
        run: |
          npm install
          npm run build
          npm run test
